[Clustering] Fixing the bug in clustering for Conv3D
tensorflow/model-optimization pull request #609
Opened 2021-01-05 11:22 UTC by wwwind

There is a bug in clustering for Conv3D. We used the layout for Conv2D and this is wrong, because tensors in Conv3D have 5 ranks, not 4. 
I added a specific to Conv3D implementation and tests.

2021-02-05 09:21 UTC, akarmi commented
Thanks. Looks like we need a similar test and fix for Conv1D.

2021-02-05 09:23 UTC, akarmi requested changes
Thanks. Looks like we need a similar test and fix for Conv1D.

2021-04-13 15:36 UTC, akarmi approved these changes

2021-04-13 15:39 UTC, akarmi commented
@psunn, please review

2021-04-13 15:45 UTC, psunn commented
LGTM, thanks!

2021-04-19 09:47 UTC, daverim commented on tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
> +     """
Nit: """Verifies that we can cluster a Conv1D layer.""" Should be a one-liner

2021-04-19 09:47 UTC, daverim commented on tensorflow_model_optimization/python/core/clustering/keras/cluster_test.py
> +     input_shape =(4, 28, 28, 28, 1)
Same as above:

2021-04-19 09:47 UTC, daverim commented on tensorflow_model_optimization/python/core/clustering/keras/clustering_registry.py
> +        axis=wt_dim-1)
Seems a little clunky with all the list comprehensions, is it possible to make this a bit more readable?

2021-04-19 15:12 UTC, wwwind commented
Hi @daverim Thanks for the review! Your comments are addressed. Please take a look.

2021-05-10 07:34 UTC, daverim commented
Hey sorry, is this PR still required? Can you rebase?

2021-05-10 15:31 UTC, wwwind commented
@googlebot I signed it!

2021-05-10 15:39 UTC, psunn commented
@googlebot I consent

2021-05-10 15:43 UTC, wwwind commented
@googlebot I consent.

2021-05-10 20:25 UTC, akarmi approved these changes

2021-05-11 05:58 UTC, daverim approved these changes

2021-06-22 07:18 UTC, merged