[clustering] Clusterable layer API
tensorflow/model-optimization pull request #616
Opened 2021-01-15 16:44 UTC by wwwind

This PR extends our support for clustering the following two user cases:

1. The user wants to specify that the bias for the dense layer should be clustered as well. 
In this case the user needs to create a new layer derived from Dense and ClusterableLayer and
provide what is needed to be clustered in the function **get_clusterable_weights**.

`
class MyDenseLayer(keras.layers.Dense, clusterable_layer.ClusterableLayer):

  def __init__(self, num_units):
    super().__init__(num_units)

  def get_clusterable_weights(self):
    # Cluster kernel and bias.
    return [('kernel', self.kernel), ('bias', self.bias)]
`

2. This user case is for a keras custom layer. We don't support a keras custom layer by default.
To be able to cluster it, the user needs to derive it from ClusterableLayer and provides two functions:
**get_clusterable_weights**, which specifies what should be clustered as in the first user case,
**get_clusterable_algorithm**, which is needed to specify the layout of the weight tensor.
The example is given below:
`
class MyCustomerableLayer(keras.layers.Layer, clusterable_layer.ClusterableLayer):

  def __init__(self, units=32):
    super(MyCustomerableLayer, self).__init__()
    self.units = units

  def build(self, input_shape):
    self.w = self.add_weight(
      shape=(input_shape[-1], self.units),
      initializer="random_normal",
      trainable=True,
    )
    self.b = self.add_weight(
      shape=(self.units,),
      initializer="random_normal",
      trainable=False
    )

  def call(self, inputs):
    return tf.matmul(inputs, self.w) + self.b

  def get_clusterable_weights(self):
    # Cluster only weights 'w'
    return [('w', self.w)]
`

Both these user cases are added as a mnist test in the new test file: mnist_customerable_test.py.

2021-02-15 17:08 UTC, akarmi requested changes
Thank you, and apologies for taking so long to review!

Can you please tidy up the description? The formatting is a bit off and makes it difficult to read. Also, the code snippet for the second use case does not include `get_clusterable_algorithm()`.

2021-02-15 17:08 UTC, akarmi commented on tensorflow_model_optimization/python/core/clustering/keras/mnist_customerable_test.py
> +# Copyright 2021 The TensorFlow Authors. All Rights Reserved.
nit: please rename to `mnist_clusterable_layer_test.py`

2021-02-24 21:58 UTC, akarmi requested changes
Thanks. Looks good. Just a minor request.

2021-02-24 21:58 UTC, akarmi commented on tensorflow_model_optimization/python/core/clustering/keras/mnist_clustering_test.py
> +    nr_of_bias_weights = _get_number_of_unique_weights(model, -1, 1)
Please, add a similar assertion check for the number of unique bias values to the one for the weights above.

2021-02-25 17:51 UTC, akarmi approved these changes
Thank you!

2021-02-25 18:26 UTC, akarmi requested changes
Apologies, I missed it initially. We need to expose ClusterableLayer in the public API, which will require exposing AbstractClusteringAlgorithm as well. The latter then needs moving out of the clustering_registry.py into its own module, to prevent exposing the implementation guts in the public API, and we should also then clean up clustering_registry.py to remove unused functions, e.g. register_new_implementation(). Any thoughts?

2021-03-01 14:53 UTC, wwwind commented
Hi @akarmi Please re-review this PR - all comments are addressed. Thanks!

2021-03-01 17:53 UTC, akarmi approved these changes
Thanks.
@daverim, as this is change affects the public API, please review it as well.

2021-03-04 10:00 UTC, akarmi approved these changes

2021-03-24 09:49 UTC, akarmi approved these changes

2021-03-24 09:50 UTC, akarmi commented
@daverim, any feedback? - we would like to merge this now.

2021-03-29 08:00 UTC, fredrec approved these changes

2021-04-13 12:47 UTC, wwwind commented
Hi @daverim I updated this PR with the merged changes. I checked the test that is left in this PR locally and it works as expected.
Could we please merge this PR ? Thanks!

2021-04-19 09:43 UTC, daverim approved these changes

2021-04-22 02:58 UTC, merged