Updated release notes with clustering items.
tensorflow/model-optimization pull request #712
Opened 2021-05-18 10:59 UTC by wwwind

In this PR we update release notes for clustering for the future release of tfmot.

2021-05-24 09:28 UTC, akarmi requested changes

2021-05-24 09:28 UTC, akarmi commented on RELEASE.md
> +* Introduced two new experimental quantization scheme for Quantization Aware Training
nit: scheme -> schemes

2021-05-24 16:46 UTC, akarmi approved these changes
Thanks

2021-05-25 09:11 UTC, daverim approved these changes

2021-06-08 09:10 UTC, daverim approved these changes

2021-06-17 14:29 UTC, merged